[tool.poetry]
name = "etl_bq"
version = "0.1.0"
description = ""
authors = ["xxxxxxxx"]

[tool.poetry.dependencies]
python = "^3.7"
apache-beam = "^2.39.0"
pyspark = "^3.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
